import FWCore.ParameterSet.Config as cms

from Analysis.VLQAna.VLQParams_cfi import * 

evtcleaner = cms.EDFilter("EventCleaner",
    runnoLabel                 = cms.InputTag("eventInfo", "evtInfoRunNumber"),
    lumisecLabel               = cms.InputTag("eventInfo", "evtInfoLumiBlock"),
    evtnoLabel                 = cms.InputTag("eventInfo", "evtInfoEventNumber"),
    trigNameLabel              = cms.InputTag("TriggerUserData", "triggerNameTree"), 
    trigBitLabel               = cms.InputTag("TriggerUserData", "triggerBitTree"), 
    BadChargedCandidateFilter  = cms.InputTag("BadChargedCandidateFilter"),
    BadPFMuonFilter            = cms.InputTag("BadPFMuonFilter"),
    metFiltersNameLabel        = cms.InputTag("METUserData", "triggerNameTree"), 
    metFiltersBitLabel         = cms.InputTag("METUserData", "triggerBitTree"), 
    lheProdName                = cms.string("externalLHEProducer"), 
    genEvtInfoProdName         = cms.string('generator'),
    vtxRhoLabel                = cms.InputTag("vertexInfo", "rho"),
    vtxZLabel                  = cms.InputTag("vertexInfo", "z"),
    vtxNdfLabel                = cms.InputTag("vertexInfo", "ndof"),
    npvLabel                   = cms.InputTag("vertexInfo", "npv"),
    puNtrueIntLabel            = cms.InputTag("eventUserData", "puNtrueInt"),
    hltORAND                   = cms.string("OR"),
    hltPaths                   = cms.vstring (
        ), 
    metFilters                 = cms.vstring (
        #"Flag_goodVertices",
        #"Flag_CSCTightHaloFilter",
        #"Flag_HBHENoiseFilter", 
        #"Flag_eeBadScFilter",
        "Flag_HBHENoiseFilter",  
        "Flag_HBHENoiseIsoFilter",  
        "Flag_EcalDeadCellTriggerPrimitiveFilter",  
        "Flag_goodVertices",  
        "Flag_eeBadScFilter",  
        "Flag_globalTightHalo2016Filter", 
        ), 
    isData                     = cms.bool(False), 
    DoPUReweightingOfficial    = cms.bool(False),
    File_PVWt                  = cms.string(''),
    File_PUDistData            = cms.string('RunII2016_PUXsec69000nb.root'),
    File_PUDistDataLow         = cms.string('RunII2016_PUXsec65550nb.root'),
    File_PUDistDataHigh        = cms.string('RunII2016_PUXsec72450nb.root'),
    File_PUDistMC              = cms.string('PUDistMC_2016_25ns_SpringMC_PUScenarioV1_PoissonOOTPU.root'),
    Hist_PVWt                  = cms.string('hpvwt_data_mc'),
    Hist_PUDistData            = cms.string('pileup'),
    Hist_PUDistMC              = cms.string('pileup'),
    cleanEvents                = cms.bool(False), 
    storeLHEWts                = cms.bool(False), 
    TtZParams                  = cms.PSet(genPartParams,TqZParams), 
    TtHParams                  = cms.PSet(genPartParams,TqHParams), 
    TbWParams                  = cms.PSet(genPartParams,TqWParams), 
    BbZParams                  = cms.PSet(genPartParams,BqZParams), 
    BbHParams                  = cms.PSet(genPartParams,BqHParams), 
    BtWParams                  = cms.PSet(genPartParams,BqWParams), 
    )
