import FWCore.ParameterSet.Config as cms

defaultAK4JetParameters = cms.PSet(
    npvLabel                = cms.InputTag("vertexInfo", "npv"),
    rhoLabel                = cms.InputTag("fixedGridRhoFastjetAll"),
    jetPtLabel              = cms.InputTag("jetsAK4CHS", "jetAK4CHSPt"),
    jetEtaLabel             = cms.InputTag("jetsAK4CHS", "jetAK4CHSEta"),
    jetPhiLabel             = cms.InputTag("jetsAK4CHS", "jetAK4CHSPhi"),
    #jetMassLabel            = cms.InputTag("jetsAK4CHS", "jetAK4CHSMass"),
    jetEnergyLabel          = cms.InputTag("jetsAK4CHS", "jetAK4CHSE"),
    jetPartonFlavourLabel   = cms.InputTag("jetsAK4CHS", "jetAK4CHSPartonFlavour"),
    jetHadronFlavourLabel   = cms.InputTag("jetsAK4CHS", "jetAK4CHSHadronFlavour"),
    jetCSVLabel             = cms.InputTag("jetsAK4CHS", "jetAK4CHSCSVv2"),
    jetCMVALabel            = cms.InputTag("jetsAK4CHS", "jetAK4CHSCMVAv2"),
    jetCvsBLabel            = cms.InputTag("jetsAK4CHS", "jetAK4CHSCvsB"),
    jetCvsLLabel            = cms.InputTag("jetsAK4CHS", "jetAK4CHSCvsL"),
    #jetDoubleBAK8Label      = cms.InputTag("jetsAK4CHS", "jetAK4CHSDoubleBAK8"),
    #jetDoubleBCA15Label     = cms.InputTag("jetsAK4CHS", "jetAK4CHSDoubleBCA15"),
    jetJECLabel             = cms.InputTag("jetsAK4CHS", "jetAK4CHSjecFactor0"),
    jetnHadEnergyLabel      = cms.InputTag("jetsAK4CHS", "jetAK4CHSneutralHadronEnergyFrac"),
    jetnEMEnergyLabel       = cms.InputTag("jetsAK4CHS", "jetAK4CHSneutralEmEnergyFrac"),
    #jetHFHadronEnergyLabel  = cms.InputTag("jetsAK4CHS", "jetAK4CHSHFHadronEnergy"),
    jetcHadEnergyLabel      = cms.InputTag("jetsAK4CHS", "jetAK4CHSchargedHadronEnergyFrac"),
    jetcEMEnergyLabel       = cms.InputTag("jetsAK4CHS", "jetAK4CHSchargedEmEnergyFrac"),
    #jetnumDaughtersLabel    = cms.InputTag("jetsAK4CHS", "jetAK4CHSnumberOfDaughters"),
    jetcMultipLabel         = cms.InputTag("jetsAK4CHS", "jetAK4CHSchargedMultiplicity"),
    jetnMultipLabel         = cms.InputTag("jetsAK4CHS", "jetAK4CHSneutralMultiplicity"),
    jetMuonEnergyLabel      = cms.InputTag("jetsAK4CHS", "jetAK4CHSMuonEnergy"),
    jetYLabel               = cms.InputTag("jetsAK4CHS", "jetAK4CHSY"),
    jetAreaLabel            = cms.InputTag("jetsAK4CHS", "jetAK4CHSjetArea"),
    jetGenJetPtLabel        = cms.InputTag("jetsAK4CHS", "jetAK4CHSGenJetPt"),
    jetGenJetEtaLabel       = cms.InputTag("jetsAK4CHS", "jetAK4CHSGenJetEta"),
    jetGenJetPhiLabel       = cms.InputTag("jetsAK4CHS", "jetAK4CHSGenJetPhi"),
    jetGenJetELabel         = cms.InputTag("jetsAK4CHS", "jetAK4CHSGenJetE"),
    jetGenJetChargeLabel    = cms.InputTag("jetsAK4CHS", "jetAK4CHSGenJetCharge"),
    )

defaultAK8GenJetSoftDropParameters = cms.PSet(
    jetPtLabel     = cms.InputTag("genJetsAK8SoftDrop"       , "genJetsAK8SoftDropPt"),    
    jetEtaLabel    = cms.InputTag("genJetsAK8SoftDrop"       , "genJetsAK8SoftDropEta"),    
    jetPhiLabel    = cms.InputTag("genJetsAK8SoftDrop"       , "genJetsAK8SoftDropPhi"),    
    jetEnergyLabel = cms.InputTag("genJetsAK8SoftDrop"       , "genJetsAK8SoftDropE"),    
    jetChargeLabel = cms.InputTag("genJetsAK8SoftDrop"       , "genJetsAK8SoftDropCharge"),    
    )

defaultAK8GenSoftDropSubjetParameters = cms.PSet(
    jetPtLabel     = cms.InputTag("genJetsAK8SoftDropSubjets", "genJetsAK8SoftDropSubJetsEta"),    
    jetEtaLabel    = cms.InputTag("genJetsAK8SoftDropSubjets", "genJetsAK8SoftDropSubJetsPhi"),    
    jetPhiLabel    = cms.InputTag("genJetsAK8SoftDropSubjets", "genJetsAK8SoftDropSubJetsPt"),    
    jetEnergyLabel = cms.InputTag("genJetsAK8SoftDropSubjets", "genJetsAK8SoftDropSubJetsE"),    
    jetChargeLabel = cms.InputTag("genJetsAK8SoftDropSubjets", "genJetsAK8SoftDropSubJetsCharge"),    
    )

defaultAK8CHSJetParameters = defaultAK4JetParameters.clone( 
    npvLabel                = cms.InputTag("vertexInfo", "npv"),
    rhoLabel                = cms.InputTag("fixedGridRhoFastjetAll"),
    jetPtLabel              = cms.InputTag("jetsAK8CHS", "jetAK8CHSPt"),
    jetEtaLabel             = cms.InputTag("jetsAK8CHS", "jetAK8CHSEta"),
    jetPhiLabel             = cms.InputTag("jetsAK8CHS", "jetAK8CHSPhi"),
    jetEnergyLabel          = cms.InputTag("jetsAK8CHS", "jetAK8CHSE"),
    jetPrunedMassLabel      = cms.InputTag("jetsAK8CHS", "jetAK8CHSprunedMass"),
    jetTrimmedMassLabel     = cms.InputTag("jetsAK8CHS", "jetAK8CHStrimmedMass"),
    jetFilteredMassLabel    = cms.InputTag("jetsAK8CHS", "jetAK8CHSfilteredMass"),
    jetSoftDropMassLabel    = cms.InputTag("jetsAK8CHS", "jetAK8CHSsoftDropMass"),
    jetPartonFlavourLabel   = cms.InputTag("jetsAK8CHS", "jetAK8CHSPartonFlavour"),
    jetHadronFlavourLabel   = cms.InputTag("jetsAK8CHS", "jetAK8CHSHadronFlavour"),
    jetCSVLabel             = cms.InputTag("jetsAK8CHS", "jetAK8CHSCSVv2"),
    jetCMVALabel            = cms.InputTag("jetsAK8CHS", "jetAK8CHSCMVAv2"),
    jetCvsBLabel            = cms.InputTag("jetsAK8CHS", "jetAK8CHSCvsB"),
    jetCvsLLabel            = cms.InputTag("jetsAK8CHS", "jetAK8CHSCvsL"),
    jetDoubleBAK8Label      = cms.InputTag("jetsAK8CHS", "jetAK8CHSDoubleBAK8"),
    jetDoubleBCA15Label     = cms.InputTag("jetsAK8CHS", "jetAK8CHSDoubleBCA15"),
    jetJECLabel             = cms.InputTag("jetsAK8CHS", "jetAK8CHSjecFactor0"),
    jetnHadEnergyLabel      = cms.InputTag("jetsAK8CHS", "jetAK8CHSneutralHadronEnergyFrac"),
    jetnEMEnergyLabel       = cms.InputTag("jetsAK8CHS", "jetAK8CHSneutralEmEnergyFrac"),
    #jetHFHadronEnergyLabel  = cms.InputTag("jetsAK8CHS", "jetAK8CHSHFHadronEnergy"),
    jetcHadEnergyLabel      = cms.InputTag("jetsAK8CHS", "jetAK8CHSchargedHadronEnergyFrac"),
    jetcEMEnergyLabel       = cms.InputTag("jetsAK8CHS", "jetAK8CHSchargedEmEnergyFrac"),
    #jetnumDaughtersLabel    = cms.InputTag("jetsAK8CHS", "jetAK8CHSnumberOfDaughters"),
    jetcMultipLabel         = cms.InputTag("jetsAK8CHS", "jetAK8CHSchargedMultiplicity"),
    jetnMultipLabel         = cms.InputTag("jetsAK8CHS", "jetAK8CHSneutralMultiplicity"),
    jetMuonEnergyLabel      = cms.InputTag("jetsAK8CHS", "jetAK8CHSMuonEnergy"),
    jetYLabel               = cms.InputTag("jetsAK8CHS", "jetAK8CHSY"),
    jetAreaLabel            = cms.InputTag("jetsAK8CHS", "jetAK8CHSjetArea"),
    jetGenJetPtLabel        = cms.InputTag("jetsAK8CHS", "jetAK8CHSGenJetPt"),
    jetGenJetEtaLabel       = cms.InputTag("jetsAK8CHS", "jetAK8CHSGenJetEta"),
    jetGenJetPhiLabel       = cms.InputTag("jetsAK8CHS", "jetAK8CHSGenJetPhi"),
    jetGenJetELabel         = cms.InputTag("jetsAK8CHS", "jetAK8CHSGenJetE"),
    jetGenJetChargeLabel    = cms.InputTag("jetsAK8CHS", "jetAK8CHSGenJetCharge"),
    )

defaultCHSJetSubstructureParameters = cms.PSet( 
    jettau1Label            = cms.InputTag("jetsAK8CHS", "jetAK8CHStau1CHS"), 
    jettau2Label            = cms.InputTag("jetsAK8CHS", "jetAK8CHStau2CHS"),  
    jettau3Label            = cms.InputTag("jetsAK8CHS", "jetAK8CHStau3CHS"),  
    jetPrunedMassLabel      = cms.InputTag("jetsAK8CHS", "jetAK8CHSprunedMassCHS"),
    jetTrimmedMassLabel     = cms.InputTag("jetsAK8CHS", "jetAK8CHStrimmedMassCHS"),
    jetFilteredMassLabel    = cms.InputTag("jetsAK8CHS", "jetAK8CHSfilteredMassCHS"),
    jetSoftDropMassLabel    = cms.InputTag("jetsAK8CHS", "jetAK8CHSsoftDropMassCHS"),
    vjetsjIdx0Label         = cms.InputTag("jetsAK8CHS", "jetAK8CHSvSubjetIndex0"),  
    vjetsjIdx1Label         = cms.InputTag("jetsAK8CHS", "jetAK8CHSvSubjetIndex1"),  
    )

defaultCHSSubjetParameters = cms.PSet(
    jetPtLabel              = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSPt"),
    jetEtaLabel             = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSEta"),
    jetPhiLabel             = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSPhi"),
    #jetMassLabel            = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSMass"),
    jetEnergyLabel          = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSE"),
    jetCSVLabel             = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSCSVv2"),
    jetCMVALabel            = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSCMVAv2"),
    jetPartonFlavourLabel   = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSPartonFlavour"),
    jetHadronFlavourLabel   = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSHadronFlavour"),
    jetGenJetPtLabel        = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSGenJetPt"),
    jetGenJetEtaLabel       = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSGenJetEta"),
    jetGenJetPhiLabel       = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSGenJetPhi"),
    jetGenJetELabel         = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSGenJetE"),
    jetGenJetChargeLabel    = cms.InputTag("subjetsAK8CHS", "subjetAK8CHSGenJetCharge"),
    )

defaultAK8PuppiJetParameters = defaultAK4JetParameters.clone( 
    npvLabel                = cms.InputTag("vertexInfo", "npv"),
    rhoLabel                = cms.InputTag("fixedGridRhoFastjetAll"),
    jetPtLabel              = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiPt"),
    jetEtaLabel             = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiEta"),
    jetPhiLabel             = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiPhi"),
    #jetMassLabel            = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiMass"),
    jetEnergyLabel          = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiE"),
    jetPrunedMassLabel      = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiprunedMass"),
    jetTrimmedMassLabel     = cms.InputTag("jetsAK8Puppi", "jetAK8PuppitrimmedMass"),
    jetFilteredMassLabel    = cms.InputTag("jetsAK8Puppi", "jetAK8PuppifilteredMass"),
    jetSoftDropMassLabel    = cms.InputTag("jetsAK8Puppi", "jetAK8PuppisoftDropMass"),
    jetPartonFlavourLabel   = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiPartonFlavour"),
    jetHadronFlavourLabel   = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiHadronFlavour"),
    jetCSVLabel             = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiCSVv2"),
    jetCMVALabel            = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiCMVAv2"),
    jetCvsBLabel            = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiCvsB"),
    jetCvsLLabel            = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiCvsL"),
    jetDoubleBAK8Label      = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiDoubleBAK8"),
    jetDoubleBCA15Label     = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiDoubleBCA15"),
    jetJECLabel             = cms.InputTag("jetsAK8Puppi", "jetAK8PuppijecFactor0"),
    jetnHadEnergyLabel      = cms.InputTag("jetsAK8Puppi", "jetAK8PuppineutralHadronEnergyFrac"),
    jetnEMEnergyLabel       = cms.InputTag("jetsAK8Puppi", "jetAK8PuppineutralEmEnergyFrac"),
    #jetHFHadronEnergyLabel  = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiHFHadronEnergy"),
    jetcHadEnergyLabel      = cms.InputTag("jetsAK8Puppi", "jetAK8PuppichargedHadronEnergyFrac"),
    jetcEMEnergyLabel       = cms.InputTag("jetsAK8Puppi", "jetAK8PuppichargedEmEnergyFrac"),
    #jetnumDaughtersLabel    = cms.InputTag("jetsAK8Puppi", "jetAK8PuppinumberOfDaughters"),
    jetcMultipLabel         = cms.InputTag("jetsAK8Puppi", "jetAK8PuppichargedMultiplicity"),
    jetnMultipLabel         = cms.InputTag("jetsAK8Puppi", "jetAK8PuppineutralMultiplicity"),
    jetMuonEnergyLabel      = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiMuonEnergy"),
    jetYLabel               = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiY"),
    jetAreaLabel            = cms.InputTag("jetsAK8Puppi", "jetAK8PuppijetArea"),
    jetGenJetPtLabel        = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiGenJetPt"),
    jetGenJetEtaLabel       = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiGenJetEta"),
    jetGenJetPhiLabel       = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiGenJetPhi"),
    jetGenJetELabel         = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiGenJetE"),
    jetGenJetChargeLabel    = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiGenJetCharge"),
    )

defaultPuppiJetSubstructureParameters = cms.PSet( 
    jettau1Label            = cms.InputTag("jetsAK8Puppi", "jetAK8Puppitau1"), 
    jettau2Label            = cms.InputTag("jetsAK8Puppi", "jetAK8Puppitau2"),  
    jettau3Label            = cms.InputTag("jetsAK8Puppi", "jetAK8Puppitau3"),  
    jetPrunedMassLabel      = cms.InputTag("jetsAK8Puppi", "jetAK8PuppiprunedMass"),
    jetTrimmedMassLabel     = cms.InputTag("jetsAK8Puppi", "jetAK8PuppitrimmedMass"),
    jetFilteredMassLabel    = cms.InputTag("jetsAK8Puppi", "jetAK8PuppifilteredMass"),
    jetSoftDropMassLabel    = cms.InputTag("jetsAK8Puppi", "jetAK8PuppisoftDropMass"),
    vjetsjIdx0Label         = cms.InputTag("jetsAK8Puppi", "jetAK8PuppivSubjetIndex0"),  
    vjetsjIdx1Label         = cms.InputTag("jetsAK8Puppi", "jetAK8PuppivSubjetIndex1"),  
    )

defaultPuppiSubjetParameters = cms.PSet(
    jetPtLabel              = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiPt"),
    jetEtaLabel             = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiEta"),
    jetPhiLabel             = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiPhi"),
    #jetMassLabel            = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiMass"),
    jetEnergyLabel          = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiE"),
    jetCSVLabel             = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiCSVv2"),
    jetCMVALabel            = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiCMVAv2"),
    jetPartonFlavourLabel   = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiPartonFlavour"),
    jetHadronFlavourLabel   = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiHadronFlavour"),
    jetGenJetPtLabel        = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiGenJetPt"),
    jetGenJetEtaLabel       = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiGenJetEta"),
    jetGenJetPhiLabel       = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiGenJetPhi"),
    jetGenJetELabel         = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiGenJetE"),
    jetGenJetChargeLabel    = cms.InputTag("subjetsAK8Puppi", "subjetAK8PuppiGenJetCharge"),
    )
