import FWCore.ParameterSet.Config as cms

from Analysis.VLQAna.PickGenPart_cfi import *
from Analysis.VLQAna.JetMaker_cfi import *
ana = cms.EDFilter("VLQAna", 
    runno                      = cms.InputTag("evtcleaner","runno"), 
    lumisec                    = cms.InputTag("evtcleaner","lumisec"), 
    evtno                      = cms.InputTag("evtcleaner","evtno"), 
    isData                     = cms.InputTag("evtcleaner","isData"), 
    hltdecision                = cms.InputTag("evtcleaner","hltdecision"), 
    evttype                    = cms.InputTag("evtcleaner","evttype"),
    evtwtGen                   = cms.InputTag("evtcleaner","evtwtGen"),
    evtwtPV                    = cms.InputTag("evtcleaner","evtwtPV"),
    evtwtPVLow                 = cms.InputTag("evtcleaner","evtwtPVLow"),
    evtwtPVHigh                = cms.InputTag("evtcleaner","evtwtPVHigh"),
    npv                        = cms.InputTag("evtcleaner","npv"),
    npuTrue                    = cms.InputTag("evtcleaner","npuTrue"),
    htHat                      = cms.InputTag("evtcleaner","htHat"),
    lhewtids                   = cms.InputTag("evtcleaner","lhewtids"),
    lhewts                     = cms.InputTag("evtcleaner","lhewts"), 
    jetAK4selParams            = defaultAK4JetSelectionParameters,
    jetAK8selParams            = defaultAK8CHSJetSelectionParameters,
    jetHTaggedselParams        = defaultCHSHJetSelectionParameters,
    jetAntiHTaggedselParams    = defaultCHSHJetSelectionParameters.clone(
      subjetCSVMin = cms.double(-1000000) ,
      subjetCSVMax = cms.double(0.605) ,
      ), 
    jetTopTaggedselParams      = defaultCHSTJetSelectionParameters.clone(
      jettau3Bytau2Max    = cms.double(0.54) ,
      subjetHighestCSVMin = cms.double(0.79) ,
      ), 
    HTMin                      = cms.double  (1000.), 
    doBTagSFUnc                = cms.bool(False), 
    storePreselEvts            = cms.bool(False), 
    doPreselOnly               = cms.bool(False), 
    )

anaPFHT800 = cms.EDFilter("VLQAna", 
    runno                      = cms.InputTag("evtcleanerPFHT800","runno"), 
    lumisec                    = cms.InputTag("evtcleanerPFHT800","lumisec"), 
    evtno                      = cms.InputTag("evtcleanerPFHT800","evtno"), 
    isData                     = cms.InputTag("evtcleanerPFHT800","isData"), 
    hltdecision                = cms.InputTag("evtcleanerPFHT800","hltdecision"), 
    evttype                    = cms.InputTag("evtcleanerPFHT800","evttype"),
    evtwtGen                   = cms.InputTag("evtcleanerPFHT800","evtwtGen"),
    evtwtPV                    = cms.InputTag("evtcleanerPFHT800","evtwtPV"),
    evtwtPVLow                 = cms.InputTag("evtcleanerPFHT800","evtwtPVLow"),
    evtwtPVHigh                = cms.InputTag("evtcleanerPFHT800","evtwtPVHigh"),
    npv                        = cms.InputTag("evtcleanerPFHT800","npv"),
    npuTrue                    = cms.InputTag("evtcleanerPFHT800","npuTrue"),
    htHat                      = cms.InputTag("evtcleanerPFHT800","htHat"),
    lhewtids                   = cms.InputTag("evtcleanerPFHT800","lhewtids"),
    lhewts                     = cms.InputTag("evtcleanerPFHT800","lhewts"), 
    jetAK4selParams            = defaultAK4JetSelectionParameters,
    jetAK8selParams            = defaultAK8CHSJetSelectionParameters,
    jetHTaggedselParams        = defaultCHSHJetSelectionParameters,
    jetAntiHTaggedselParams    = defaultCHSHJetSelectionParameters.clone(
      subjetCSVMin = cms.double(-1000000) ,
      subjetCSVMax = cms.double(0.605) ,
      ), 
    jetTopTaggedselParams      = defaultCHSTJetSelectionParameters.clone(
      jettau3Bytau2Max    = cms.double(0.54) ,
      subjetHighestCSVMin = cms.double(0.79) ,
      ), 
    HTMin                      = cms.double  (1000.), 
    doBTagSFUnc                = cms.bool(False), 
    storePreselEvts            = cms.bool(False), 
    doPreselOnly               = cms.bool(False), 
    )
